@startuml
  Class Fabrica{
    + string nombre
    + template<class Prod> Prod* crear()
    + void instalacion()
    + void seleccionComponentes()
    + void ensambladoComponentes()
    + void instalacionConfiguracionSoftware()
    + void empaquetadoComputador()
  }
  Class Laptop{
    friend class Fabrica
    +queSoy()
    - Laptop():Fabrica
  }
  Class Desktop{
    friend class Fabrica
    +queSoy()
    - Desktop():Fabrica
  }
  Class Netbook{
    friend class Fabrica
    +queSoy()
    - Netbook():Fabrica
  }
  Class Tablet{
    friend class Fabrica
    +queSoy()
    - Tablet():Fabrica
  }
  Class Rack{
    friend class Fabrica
    +queSoy()
    - Rack():Fabrica
  }
  Class Tower{
    friend class Fabrica
    +queSoy()
    - Tower():Fabrica
  }

Fabrica --> Laptop :returns
Laptop --|> Fabrica

Fabrica --> Desktop :returns
Desktop --|> Fabrica

Fabrica --> Netbook :returns
Netbook --|> Fabrica

Fabrica --> Tablet :returns
Tablet --|> Fabrica

Fabrica --> Rack :returns
Rack --|> Fabrica

Fabrica --> Tower :returns
Tower --|> Fabrica
@enduml
