@startuml
  Class Creator{
    - virtual  Product* createProduct(int type)
    +  Product* factoryMethod(int type)
  }
  Class CreatorA{
    +  Product* createProduct(int type)
  }
  Class Product{
    + void operatation()
    + void operatation2()
  }
  Creator <.. CreatorA 
  CreatorA --> Product :returns
@enduml
